### ISSUE TITLE
TODO TODO TODO

### ISSUE THREAD

**Issue by VladDen4** [VladDen4/ColoredConsole#3]
- [x] [Readme] Change the example commands in Usage (table?)
- [x] [Readme] Writer.CreateLogfile is optional, but will not log to file
- [ ] [Writer.CreateLogfile] add the ability to enter an empty _directoryName parameter. Logging will be along the path .\logs\"name".log
- [x] Make a package for VS (nuget)

![todo meme](https://user-images.githubusercontent.com/33760265/229247553-2479f6bb-2326-4110-ae9a-49e7d42a1536.jpg)

**Comment by VladDen4** [comment]
- [x] Watch Movie Pirates of the Caribbean

**Comment by VladDen4** [comment]
The project has been added to NuGet as a package. See https://www.nuget.org/packages/Tise.Util.ColoredConsole/1.1.2 for details.
